replicaCount: 1

image:
  repository: 445567099825.dkr.ecr.us-east-1.amazonaws.com/customer-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

env:
  DB_HOST: "my-rds-instance.cshc0wimskn2.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_USERNAME: "admin"
  DB_NAME: "mydatabase"
  DB_PASSWORD: "2cd8baefe644dd761b04ae3453a5039b"
  DB_PASSWORD_SECRET_NAME: "db-password-secret"
  DB_PASSWORD_SECRET_KEY: "password"
